CREATE TABLE `siemprea_bspi_gestion_hospitalaria`.`movimiento_inventario` (
  `MOVIM_INV_COD` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PROD_DETA_COD` BIGINT UNSIGNED NOT NULL,
  `MOVIM_INV_FARM_COD_ORGI` BIGINT NULL,
  `MOVIM_INV_FARM_COD_DEST` BIGINT NULL,
  `MOVIM_INV_INGR` BIGINT NULL,
  `MOVIM_INV_EGR` BIGINT NULL,
  `MOVIM_INV_STOCK` BIGINT NOT NULL,
  `MOVIM_INV_LOGIC_ESTADO` CHAR(2) NOT NULL,
  `US_COD_CREATED_UPDATED` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`MOVIM_INV_COD`),
  INDEX `movim_inv_prod_deta_cod_foregin_idx` (`PROD_DETA_COD` ASC) VISIBLE,
  CONSTRAINT `movim_inv_prod_deta_cod_foregin`
    FOREIGN KEY (`PROD_DETA_COD`)
    REFERENCES `siemprea_bspi_gestion_hospitalaria`.`productos_detalle` (`PROD_DETA_COD`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);
