ALTER TABLE `siemprea_bspi_gestion_hospitalaria`.`prescripcion` 
ADD COLUMN `PRESCRIPCION_HORA` TIME NULL DEFAULT NOT NULL AFTER `PRESCRIPCION_FECHA`,
ADD COLUMN `PRESCRIPCION_EVOLUCION` VARCHAR(255) NULL DEFAULT NULL AFTER `PRESCRIPCION_TOTAL_ITEMS`,
CHANGE COLUMN `HOSPITAL_COD` `HOSPITAL_COD` BIGINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `DOCTOR_COD` `DOCTOR_COD` BIGINT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `PRESCRIPCION_DOCTOR_FIRMA` `PRESCRIPCION_DOCTOR_FIRMA` VARCHAR(255) NULL DEFAULT NULL ,
CHANGE COLUMN `PRESCRIPCION_PACIENTE_FIRMA` `PRESCRIPCION_PACIENTE_FIRMA` VARCHAR(255) NULL DEFAULT NULL ;
