CREATE TABLE `siemprea_bspi_gestion_hospitalaria`.`productos` (
  `PRODUCTO_COD` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id de la tabla producto',
  `CATEGORIA_COD` BIGINT NOT NULL,
  `PRODUCTO_NOM` VARCHAR(255) NOT NULL,
  `PRODUCTO_CLAVE` VARCHAR(255) NULL,
  `PRODUCTO_PVP` DECIMAL(18,2) NOT NULL,
  `PRODUCTO_LOGIC_ESTADO` CHAR(2) NOT NULL,
  `US_COD_CREATED_UPDATED` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`PRODUCTO_COD`),
  INDEX `productos_categoria_cod_foreign_idx` (`CATEGORIA_COD` ASC) VISIBLE,
  CONSTRAINT `productos_categoria_cod_foreign`
    FOREIGN KEY (`CATEGORIA_COD`)
    REFERENCES `siemprea_bspi_gestion_hospitalaria`.`categoria` (`CATEGORIA_COD`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);