ALTER TABLE `siemprea_bspi_gestion_hospitalaria`.`citas` 
ADD COLUMN `CITA_TICKET_CONSULTA` INT NOT NULL DEFAULT 0 AFTER `updated_at`,
ADD COLUMN `CITA_TICKET_EMERGENCIA` INT NOT NULL DEFAULT 0 AFTER `CITA_TICKET_CONSULTA`;
