CREATE TABLE `unidad` (
  `UNIDAD_COD` bigint NOT NULL AUTO_INCREMENT,
  `TIPOUNIDAD_COD` bigint NOT NULL,
  `UNIDAD_NOM` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `UNIDAD_SIMB` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `UNIDAD_EQUIV` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UNIDAD_OBS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UNIDAD_LOGIC_ESTADO` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `US_COD_CREATED_UPDATED` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`UNIDAD_COD`),
  UNIQUE KEY `UNIDAD-SIMBOLO_UNIQUE` (`UNIDAD_SIMBOLO`),
  KEY `unidad_tipounidad_cod_foreign_idx` (`TIPOUNIDAD_COD`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

