ALTER TABLE `siemprea_bspi_gestion_hospitalaria`.`prescripcion` 
DROP COLUMN `PACIENTE_COD`,
ADD COLUMN `PRESCRIPCION_TOTAL_ITEMS` BIGINT NOT NULL AFTER `DOCTOR_COD`,
ADD COLUMN `PRESCRIPCION_FIRMA` VARCHAR(255) NOT NULL AFTER `PRESCRIPCION_FECHA`,
CHANGE COLUMN `DOCTOR_COD` `DOCTOR_COD` BIGINT UNSIGNED NOT NULL AFTER `CITA_COD`,
CHANGE COLUMN `PRESCRIPCION_FCHA_CTUAL` `PRESCRIPCION_FECHA` DATE NOT NULL ;
