ALTER TABLE `siemprea_bspi_gestion_hospitalaria`.`diagnosticos` 
ADD COLUMN `DIAGNOSTICO_PRESUNTIVO` INT NULL AFTER `CIE_COD`,
ADD COLUMN `DIAGNOSTICO_DEFINITIVO` INT NULL AFTER `DIAGNOSTICO_PRESUNTIVO`;