CREATE TABLE `siemprea_bspi_gestion_hospitalaria`.`categoria` (
  `CATEGORIA_COD` BIGINT NOT NULL AUTO_INCREMENT,
  `CATEGORIA_NOM` VARCHAR(255) NOT NULL,
  `CATEGORIA_OBS` VARCHAR(255) NULL DEFAULT NULL,
  `CATEGORIA_LOGIC_ESTADO` CHAR(2) NOT NULL,
  `US_COD_CREATED_UPDATED` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`CATEGORIA_COD`));
