CREATE TABLE `siemprea_bspi_gestion_hospitalaria`.`detalle_movimiento` (
  `DETALLEMOVIMIENTO_COD` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MOVIMIENTO_COD` BIGINT UNSIGNED NOT NULL,
  `PRODUCTO_DETALLE_COD` BIGINT UNSIGNED NOT NULL,
  `DETALLEMOVIMIENTO_CANTIDAD` BIGINT NOT NULL,
  `DETALLEMOVIMIENTO_STOCK_FARMACIA_ORIGEN` BIGINT NULL DEFAULT 0,
  `DETALLEMOVIMIENTO_STOCK_FARMACIA_DESTINO` BIGINT NULL DEFAULT 0,
  `DETALLEMOVIMIENTO_LOGIC_ESTADO` CHAR(2) NOT NULL,
  `US_COD_CREATED_UPDATED` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`DETALLEMOVIMIENTO_COD`),
  INDEX `detalle_movimiento_movimiento_cod_foreing_idx` (`MOVIMIENTO_COD` ASC) VISIBLE,
  INDEX `detalle_movimiento_producto_detalle_cod_foreing_idx` (`PRODUCTO_DETALLE_COD` ASC) VISIBLE,
  CONSTRAINT `detalle_movimiento_movimiento_cod_foreing`
    FOREIGN KEY (`MOVIMIENTO_COD`)
    REFERENCES `siemprea_bspi_gestion_hospitalaria`.`movimiento` (`MOVIMIENTO_COD`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `detalle_movimiento_producto_detalle_cod_foreing`
    FOREIGN KEY (`PRODUCTO_DETALLE_COD`)
    REFERENCES `siemprea_bspi_gestion_hospitalaria`.`producto_detalle` (`PRODUCTO_DETALLE_COD`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);
