CREATE TABLE `siemprea_bspi_gestion_hospitalaria`.`prescripcion_detalle` (
  `PRESC_DETA_COD` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PRESCRIPCION_COD` BIGINT UNSIGNED NOT NULL,
  `FARMACIA_COD` BIGINT UNSIGNED NOT NULL,
  `PROD_DETA_COD` BIGINT UNSIGNED NOT NULL,
  `PRESC_DETA_STOCK` BIGINT NOT NULL,
  `PRESC_DETA_CANT` BIGINT NOT NULL,
  `PRESC_DETA_PVP` DECIMAL(18,2) NOT NULL,
  `PRESC_DETA_TOTAL` DECIMAL(18,2) NOT NULL,
  `PRESC_DETA_OBS` VARCHAR(255) NULL,
  `PRESC_DETA_LOGIC_ESTADO` CHAR(2) NOT NULL,
  `US_COD_CREATED_UPDATED` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`PRESC_DETA_COD`),
  INDEX `presc_deta_prescripcion_cod_foregin_idx` (`PRESCRIPCION_COD` ASC) VISIBLE,
  INDEX `presc_deta_farmacia_cod_foregin_idx` (`FARMACIA_COD` ASC) VISIBLE,
  CONSTRAINT `presc_deta_prescripcion_cod_foregin`
    FOREIGN KEY (`PRESCRIPCION_COD`)
    REFERENCES `siemprea_bspi_gestion_hospitalaria`.`prescripcion` (`PRESCRIPCION_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `presc_deta_farmacia_cod_foregin`
    FOREIGN KEY (`FARMACIA_COD`)
    REFERENCES `siemprea_bspi_gestion_hospitalaria`.`farmacia` (`FARMACIA_COD`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);
