CREATE TABLE `siemprea_bspi_datgen`.`tipo_unidad` (
  `TIPOUNIDAD_COD` BIGINT NOT NULL AUTO_INCREMENT,
  `TIPOUNIDAD_NOM` VARCHAR(255) NOT NULL,
  `TIPOUNIDAD_OBS` VARCHAR(255) NULL DEFAULT NULL,
  `TIPOUNIDAD_LOGIC_ESTADO` CHAR(2) NOT NULL,
  `US_COD_CREATED_UPDATED` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`TIPOUNIDAD_COD`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;
