ALTER TABLE `siemprea_bspi_gestion_hospitalaria`.`prescripcion` 
ADD COLUMN `PRESCRIPCION_PACIENTE_FIRMA` VARCHAR(255) NOT NULL AFTER `PRESCRIPCION_DOCTOR_FIRMA`,
CHANGE COLUMN `PRESCRIPCION_FIRMA` `PRESCRIPCION_DOCTOR_FIRMA` VARCHAR(255) NOT NULL ,
CHANGE COLUMN `US_COD_CREATED_UPDATED` `US_COD_CREATED_UPDATED` VARCHAR(10) NOT NULL ;
