CREATE TABLE `siemprea_bspi_gestion_hospitalaria`.`farmacia` (
  `FARMACIA_COD` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FARMACIA_NOM` VARCHAR(255) NOT NULL,
  `FARMACIA_TELF` VARCHAR(255) NULL DEFAULT NULL,
  `FARMACIA_DIREC` VARCHAR(255) NULL DEFAULT NULL,
  `FARMACIA_EMAIL` VARCHAR(255) NULL DEFAULT NULL,
  `FARMACIA_OBS` VARCHAR(255) NULL DEFAULT NULL,
  `FARMACIA_WEB_PAGE` VARCHAR(255) NULL DEFAULT NULL,
  `FARMACIA_LOGIC_ESTADO` CHAR(2) NOT NULL,
  `US_COD_CREATED_UPDATED` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP DEFAULT NULL,
  `updated_at` TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (`FARMACIA_COD`));
