CREATE TABLE `siemprea_bspi_gestion_hospitalaria`.`tipo_movimiento` (
  `TIPOMOVIMIENTO_COD` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TIPOMOVIMIENTO_NOMBRE` VARCHAR(255) NOT NULL,
  `TIPOMOVIMIENTO_OBS` VARCHAR(255) NULL DEFAULT NULL,
  `TIPOMOVIMIENTO_ABREVIATURA` CHAR(3) NOT NULL,
  `TIPOMOVIMIENTO_LOGIC_ESTADO` VARCHAR(10) NOT NULL,
  `US_COD_CREATED_UPDATED` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`TIPOMOVIMIENTO_COD`));
