USE siemprea_bspi_datgen;
/*A -> ACTIVO I -> INACTIVO */
ALTER TABLE organizaciones ADD COLUMN ORGANIZACION_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';
ALTER TABLE tipos_de_organismo ADD COLUMN TIPO_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';
ALTER TABLE tipos_de_organizacion ADD COLUMN TIPO_LOGIC_ESTADO CHAR
ALTER TABLE organismos ADD COLUMN ORGANISMO_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';
ALTER TABLE paises ADD COLUMN PAIS_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';
ALTER TABLE cargos_en_organismos ADD COLUMN CARGO_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';
ALTER TABLE gestiones ADD COLUMN GESTION_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';
ALTER TABLE usuarios_roles ADD COLUMN USUARIOSROLES_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE organismos_y_contactos ADD COLUMN ORG_Y_CON_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE users ADD COLUMN USER_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE tipos_de_sangre ADD COLUMN TSANGRE_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE religiones ADD COLUMN RELIGION_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE grupos_culturales ADD COLUMN GCULTURAL_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE tipos_de_casa ADD COLUMN TIPOCASA_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE talla_camisa ADD COLUMN TALLACAMISA_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE talla_pantalon ADD COLUMN TALLAPANTALON_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE talla_zapato ADD COLUMN TALLAZAPATO_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE movilizaciones ADD COLUMN MOVILIZACION_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE tipos_de_casa ADD COLUMN TIPOCASA_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE identificaciones_y_usuarios ADD COLUMN IDENTIFICACIONESUSUARIO_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE gestiones_y_usuarios ADD COLUMN GESTIONUSUARIO_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE DISCAPACIDADES ADD COLUMN DISCAPACIDAD_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE casas ADD COLUMN CASA_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE tipos_de_organizacion ADD COLUMN TIPOORGANIZACION_LOGIC_ESTADO CHAR
ALTER TABLE provincias ADD COLUMN PROVINCIA_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE cantones ADD COLUMN CANTON_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

ALTER TABLE parroquias ADD COLUMN PARR_LOGIC_ESTADO CHAR
(2) DEFAULT 'A';

/*SCRIPT PARA AÑADIR CAMPOS DE TABLA USUARIO A TABLA USER*/
ALTER TABLE siemprea_bspi_datgen.users
ADD COLUMN US_COD VARCHAR
(10) NOT NULL AFTER updated_at,
ADD COLUMN US_FOTO LONGTEXT NULL DEFAULT NULL AFTER US_COD,
ADD COLUMN US_CEDULA_PDF VARCHAR
(30) NOT NULL AFTER US_FOTO,
ADD COLUMN US_MSP_PDF VARCHAR
(30) NOT NULL AFTER US_CEDULA_PDF,
ADD COLUMN US_CONADIS_PDF VARCHAR
(30) NOT NULL AFTER US_MSP_PDF,
ADD COLUMN US_ALIAS VARCHAR
(20) NOT NULL AFTER US_CONADIS_PDF,
ADD COLUMN US_APELL VARCHAR
(100) NULL DEFAULT NULL AFTER US_ALIAS,
ADD COLUMN US_APELL1 VARCHAR
(50) NOT NULL AFTER US_APELL,
ADD COLUMN US_APELL2 VARCHAR
(50) NOT NULL AFTER US_APELL1,
ADD COLUMN US_NOM VARCHAR
(100) NULL DEFAULT NULL AFTER US_APELL2,
ADD COLUMN US_NOM1 VARCHAR
(50) NOT NULL AFTER US_NOM,
ADD COLUMN US_NOM2 VARCHAR
(50) NOT NULL AFTER US_NOM1,
ADD COLUMN US_FNAC DATE NOT NULL AFTER US_NOM2,
ADD COLUMN US_LNACIMIENTO VARCHAR
(20) NOT NULL AFTER US_FNAC,
ADD COLUMN PAIS_COD VARCHAR
(10) NOT NULL AFTER US_LNACIMIENTO,
ADD COLUMN PARR_COD VARCHAR
(10) NOT NULL AFTER PAIS_COD,
ADD COLUMN US_DIR LONGTEXT NOT NULL AFTER PARR_COD,
ADD COLUMN US_URB_O_RURAL VARCHAR
(1) NOT NULL AFTER US_DIR,
ADD COLUMN US_TELF VARCHAR
(12) NOT NULL AFTER US_URB_O_RURAL,
ADD COLUMN US_CONTACTO_EMERG LONGTEXT NOT NULL AFTER US_TELF,
ADD COLUMN US_TELF_EMERG LONGTEXT NOT NULL AFTER US_CONTACTO_EMERG,
ADD COLUMN US_CEL VARCHAR
(12) NOT NULL AFTER US_TELF_EMERG,
ADD COLUMN US_EMAIL VARCHAR
(50) NOT NULL AFTER US_CEL,
ADD COLUMN US_EMAIL2 VARCHAR
(50) NOT NULL AFTER US_EMAIL,
ADD COLUMN US_WEB VARCHAR
(50) NOT NULL AFTER US_EMAIL2,
ADD COLUMN US_WSPAISAREA VARCHAR
(10) NOT NULL AFTER US_WEB,
ADD COLUMN US_WSCEL VARCHAR
(12) NOT NULL AFTER US_WSPAISAREA,
ADD COLUMN US_SEXO VARCHAR
(1) NOT NULL AFTER US_WSCEL,
ADD COLUMN US_ECIVIL VARCHAR
(1) NOT NULL AFTER US_SEXO,
ADD COLUMN TSANGRE_COD VARCHAR
(10) NOT NULL AFTER US_ECIVIL,
ADD COLUMN RELIGION_COD VARCHAR
(10) NOT NULL AFTER TSANGRE_COD,
ADD COLUMN US_PORC_DISCAPACIDAD VARCHAR
(6) NOT NULL AFTER RELIGION_COD,
ADD COLUMN US_CONADIS_DISCAPACIDAD VARCHAR
(10) NOT NULL AFTER US_PORC_DISCAPACIDAD,
ADD COLUMN US_MSP_DISCAPACIDAD VARCHAR
(10) NOT NULL AFTER US_CONADIS_DISCAPACIDAD,
ADD COLUMN US_ESTATURA_METROS VARCHAR
(6) NOT NULL AFTER US_MSP_DISCAPACIDAD,
ADD COLUMN US_PESO_KG VARCHAR
(6) NOT NULL AFTER US_ESTATURA_METROS,
ADD COLUMN TALLACAMISA_COD VARCHAR
(10) NOT NULL AFTER US_PESO_KG,
ADD COLUMN TALLAPANTALON_COD VARCHAR
(10) NOT NULL AFTER TALLACAMISA_COD,
ADD COLUMN TALLAZAPATO_COD VARCHAR
(10) NOT NULL AFTER TALLAPANTALON_COD,
ADD COLUMN MOVILIZACION_COD VARCHAR
(10) NOT NULL AFTER TALLAZAPATO_COD,
ADD COLUMN CASA_COD VARCHAR
(10) NOT NULL AFTER MOVILIZACION_COD,
ADD COLUMN TIPOCASA_COD VARCHAR
(10) NOT NULL AFTER CASA_COD,
ADD COLUMN US_REFERENCIA_DOMICILIO LONGTEXT NOT NULL AFTER TIPOCASA_COD,
ADD COLUMN US_LATITUD VARCHAR
(30) NOT NULL AFTER US_REFERENCIA_DOMICILIO,
ADD COLUMN US_LONGITUD VARCHAR
(30) NOT NULL AFTER US_LATITUD,
ADD COLUMN US_ZOOM VARCHAR
(3) NOT NULL AFTER US_LONGITUD,
ADD COLUMN US_ACTIVO VARCHAR
(1) NULL DEFAULT NULL AFTER US_ZOOM,
ADD COLUMN US_TRABAJADOR_BSPI VARCHAR
(1) NOT NULL DEFAULT 'S' AFTER US_ACTIVO,
ADD COLUMN US_CLAVE VARCHAR
(255) NOT NULL AFTER US_TRABAJADOR_BSPI,
ADD COLUMN US_OBS LONGTEXT NULL DEFAULT NULL AFTER US_CLAVE,
ADD COLUMN FECHA DATE NULL DEFAULT NULL AFTER US_OBS,
ADD COLUMN HORA TIME NULL DEFAULT NULL AFTER FECHA,
ADD COLUMN TIPO VARCHAR
(10) NULL DEFAULT NULL AFTER HORA,
ADD COLUMN USUARIO VARCHAR
(10) NULL DEFAULT NULL AFTER TIPO,
ADD COLUMN GCULTURAL_COD VARCHAR
(10) NOT NULL AFTER USUARIO,
ADD COLUMN US_ULTIMO_ANIO_APROBADO VARCHAR
(2) NOT NULL AFTER GCULTURAL_COD,
ADD COLUMN US_BARRIO LONGTEXT NOT NULL AFTER US_ULTIMO_ANIO_APROBADO,
ADD COLUMN ID_COD VARCHAR
(10) NOT NULL AFTER US_BARRIO;




/*SCRIPT PARA INGRESAR DATOS DE USER*/
/*los que tienen el email en email*/
INSERT INTO users
    (name,email, password,created_at, updated_at, US_COD, US_FOTO, US_CEDULA_PDF,
    US_MSP_PDF, US_CONADIS_PDF, US_ALIAS, US_APELL, US_APELL1, US_APELL2, US_NOM, US_NOM1,
    US_NOM2, US_FNAC, US_LNACIMIENTO, PAIS_COD, PARR_COD, US_DIR, US_URB_O_RURAL, US_TELF,
    US_CONTACTO_EMERG, US_TELF_EMERG, US_CEL, US_EMAIL, US_EMAIL2, US_WEB, US_WSPAISAREA, US_WSCEL,
    US_SEXO, US_ECIVIL, TSANGRE_COD, RELIGION_COD, US_PORC_DISCAPACIDAD, US_CONADIS_DISCAPACIDAD,
    US_MSP_DISCAPACIDAD, US_ESTATURA_METROS, US_PESO_KG, TALLACAMISA_COD, TALLAPANTALON_COD, MOVILIZACION_COD,
    CASA_COD, TIPOCASA_COD, US_REFERENCIA_DOMICILIO, US_LATITUD, US_LONGITUD, US_ZOOM, US_ACTIVO, US_TRABAJADOR_BSPI,
    US_CLAVE, US_OBS, FECHA, HORA, TIPO, USUARIO,GCULTURAL_COD,US_ULTIMO_ANIO_APROBADO, US_BARRIO
    )
SELECT us.US_NOM, us.US_EMAIL , '$2y$10$McqZjhqs1ELrqUNGU6zt6ecpHdg/x1Jf23CF.Lll.UeMTNciyKvOq', '2020-04-26 01:56:04', '2020-04-26 01:56:04', us.US_COD, us.US_FOTO, us.US_CEDULA_PDF,
    us.US_MSP_PDF, us.US_CONADIS_PDF, us.US_ALIAS, us.US_APELL, us.US_APELL1, us.US_APELL2, us.US_NOM, us.US_NOM1,
    us.US_NOM2, us.US_FNAC, us.US_LNACIMIENTO, us.PAIS_COD, us.PARR_COD, us.US_DIR, us.US_URB_O_RURAL, us.US_TELF,
    us.US_CONTACTO_EMERG, us.US_TELF_EMERG, us.US_CEL, us.US_EMAIL, us.US_EMAIL2, us.US_WEB, us.US_WSPAISAREA, us.US_WSCEL,
    us.US_SEXO, us.US_ECIVIL, us.TSANGRE_COD, us.RELIGION_COD, us.US_PORC_DISCAPACIDAD, us.US_CONADIS_DISCAPACIDAD,
    us.US_MSP_DISCAPACIDAD, us.US_ESTATURA_METROS, us.US_PESO_KG, us.TALLACAMISA_COD, us.TALLAPANTALON_COD, us.MOVILIZACION_COD,
    us.CASA_COD, us.TIPOCASA_COD, us.US_REFERENCIA_DOMICILIO, us.US_LATITUD, us.US_LONGITUD, us.US_ZOOM, us.US_ACTIVO, us.US_TRABAJADOR_BSPI,
    us.US_CLAVE, us.US_OBS, us.FECHA, us.HORA, us.TIPO, us.USUARIO, us.GCULTURAL_COD, us.US_ULTIMO_ANIO_APROBADO, us.US_BARRIO
FROM usuarios us
where us.US_EMAIL != ''

/*los que tienen el email en email2*/

INSERT INTO users
    (name,email, password,created_at, updated_at, US_COD, US_FOTO, US_CEDULA_PDF,
    US_MSP_PDF, US_CONADIS_PDF, US_ALIAS, US_APELL, US_APELL1, US_APELL2, US_NOM, US_NOM1,
    US_NOM2, US_FNAC, US_LNACIMIENTO, PAIS_COD, PARR_COD, US_DIR, US_URB_O_RURAL, US_TELF,
    US_CONTACTO_EMERG, US_TELF_EMERG, US_CEL, US_EMAIL, US_EMAIL2, US_WEB, US_WSPAISAREA, US_WSCEL,
    US_SEXO, US_ECIVIL, TSANGRE_COD, RELIGION_COD, US_PORC_DISCAPACIDAD, US_CONADIS_DISCAPACIDAD,
    US_MSP_DISCAPACIDAD, US_ESTATURA_METROS, US_PESO_KG, TALLACAMISA_COD, TALLAPANTALON_COD, MOVILIZACION_COD,
    CASA_COD, TIPOCASA_COD, US_REFERENCIA_DOMICILIO, US_LATITUD, US_LONGITUD, US_ZOOM, US_ACTIVO, US_TRABAJADOR_BSPI,
    US_CLAVE, US_OBS, FECHA, HORA, TIPO, USUARIO,GCULTURAL_COD,US_ULTIMO_ANIO_APROBADO, US_BARRIO
    )
SELECT us.US_NOM, us.US_EMAIL2 , '$2y$10$McqZjhqs1ELrqUNGU6zt6ecpHdg/x1Jf23CF.Lll.UeMTNciyKvOq', '2020-04-26 01:56:04', '2020-04-26 01:56:04', us.US_COD, us.US_FOTO, us.US_CEDULA_PDF,
    us.US_MSP_PDF, us.US_CONADIS_PDF, us.US_ALIAS, us.US_APELL, us.US_APELL1, us.US_APELL2, us.US_NOM, us.US_NOM1,
    us.US_NOM2, us.US_FNAC, us.US_LNACIMIENTO, us.PAIS_COD, us.PARR_COD, us.US_DIR, us.US_URB_O_RURAL, us.US_TELF,
    us.US_CONTACTO_EMERG, us.US_TELF_EMERG, us.US_CEL, us.US_EMAIL, us.US_EMAIL2, us.US_WEB, us.US_WSPAISAREA, us.US_WSCEL,
    us.US_SEXO, us.US_ECIVIL, us.TSANGRE_COD, us.RELIGION_COD, us.US_PORC_DISCAPACIDAD, us.US_CONADIS_DISCAPACIDAD,
    us.US_MSP_DISCAPACIDAD, us.US_ESTATURA_METROS, us.US_PESO_KG, us.TALLACAMISA_COD, us.TALLAPANTALON_COD, us.MOVILIZACION_COD,
    us.CASA_COD, us.TIPOCASA_COD, us.US_REFERENCIA_DOMICILIO, us.US_LATITUD, us.US_LONGITUD, us.US_ZOOM, us.US_ACTIVO, us.US_TRABAJADOR_BSPI,
    us.US_CLAVE, us.US_OBS, us.FECHA, us.HORA, us.TIPO, us.USUARIO, us.GCULTURAL_COD, us.US_ULTIMO_ANIO_APROBADO, us.US_BARRIO
FROM usuarios us
where us.US_EMAIL = ''

INSERT INTO 
siemprea_bspi_datgen.gestiones_y_usuarios

    (GESTION_COD, US_COD, USROL_COD, GESTIONUS_ACTIVO,GESTIONUS_OBS, FECHA, HORA, TIPO, USUARIO)
VALUES
    ('DATGEN', '8309171641', 'ADMIN', 'S', '', '2020-04-25', '06:38:40', 'ADMIN', '');


--TABLAS DE AUDITORIA
CREATE TABLE log_usuarios
(
    LOG_USUARIO_ID int
    auto_increment primary key,
    US_COD VARCHAR
    (10) not null,
    US_NOM VARCHAR
    (100) not null,
    MODULO_NOM LONGTEXT not null,
    FORMULARIO_NOM LONGTEXT not null,
    FORMULARIO_NOM_SISTEMA LONGTEXT not null,
    ACCION VARCHAR
    (50) not null,
    created_at TIMESTAMP not null,
    updated_at TIMESTAMP not null
);

    CREATE TABLE formularios
    (
        FORMULARIO_ID int
        auto_increment primary key,
    MODULO_COD VARCHAR
        (20) not null,
	FORMULARIO_NOM VARCHAR
        (100) not null,
    FORMULARIO_UBICACION_COMPONENTE LONGTEXT not null,
    FORMULARIO_UBICACION_CONTROLLER LONGTEXT not null,
    FORMULARIO_UBICACION_MODEL LONGTEXT not null,
    created_at TIMESTAMP not null,
    updated_at TIMESTAMP not null
);
        ALTER TABLE siemprea_bspi_datgen.log_usuarios
        DROP COLUMN FORMULARIO_NOM_SISTEMA;




        ALTER TABLE siemprea_bspi_datgen.users 
DROP INDEX users_email_unique ;


        INSERT INTO siemprea_bspi_datgen.formularios
            (MODULO_COD, FORMULARIO_NOM, FORMULARIO_UBICACION_COMPONENTE, FORMULARIO_UBICACION_CONTROLLER, FORMULARIO_UBICACION_MODEL, created_at, updated_at)
        VALUES
            ('DATGEN', 'Casas', 'resources\js\components\datosGenerales\configuraciones\Casas.vue', 'app\Http\Controllers\DatosGenerales\Usuarios\CasaApiController.php', 'app\DatosGenerales\Usuarios\Casa.php', '2020-05-06 00:00:00', '2020-05-06 00:00:00');

        INSERT INTO siemprea_bspi_datgen.formularios
            (MODULO_COD, FORMULARIO_NOM, FORMULARIO_UBICACION_COMPONENTE, FORMULARIO_UBICACION_CONTROLLER, FORMULARIO_UBICACION_MODEL, created_at, updated_at)
        VALUES
            ('DATGEN', 'Casas', 'resources\js\components\datosGenerales\configuraciones\Casas.vue', 'app\Http\Controllers\DatosGenerales\Usuarios\CasaApiController.php', 'app\DatosGenerales\Usuarios\Casa.php', '2020-05-06 00:00:00', '2020-05-06 00:00:00');

        INSERT INTO siemprea_bspi_datgen.formularios
            (MODULO_COD, FORMULARIO_NOM, FORMULARIO_UBICACION_COMPONENTE, FORMULARIO_UBICACION_CONTROLLER, FORMULARIO_UBICACION_MODEL, created_at, updated_at)
        VALUES
            ('DATGEN', 'Discapacidades', 'resources\js\components\datosGenerales\configuraciones\Discapacidades.vue', 'app\Http\Controllers\DatosGenerales\Usuarios\DiscapacidadApiController.php', 'app\DatosGenerales\Usuarios\Discapacidad.php', '2020-05-06 00:00:00', '2020-05-06 00:00:00');
        INSERT INTO siemprea_bspi_datgen.formularios
            (MODULO_COD, FORMULARIO_NOM, FORMULARIO_UBICACION_COMPONENTE, FORMULARIO_UBICACION_CONTROLLER, FORMULARIO_UBICACION_MODEL, created_at, updated_at)
        VALUES
            ('DATGEN', 'GruposCulturales', 'resources\js\components\datosGenerales\configuraciones\GruposCulturales.vue', 'app\Http\Controllers\DatosGenerales\Usuarios\GruposCulturalesApiController.php', 'app\DatosGenerales\Usuarios\GruposCulturales.php', '2020-05-06 00:00:00', '2020-05-06 00:00:00');
        INSERT INTO siemprea_bspi_datgen.formularios
            (MODULO_COD, FORMULARIO_NOM, FORMULARIO_UBICACION_COMPONENTE, FORMULARIO_UBICACION_CONTROLLER, FORMULARIO_UBICACION_MODEL, created_at, updated_at)
        VALUES
            ('DATGEN', 'Movilizaciones', 'resources\js\components\datosGenerales\configuraciones\Movilizaciones.vue', 'app\Http\Controllers\DatosGenerales\Usuarios\MovilizacionApiController.php', 'app\DatosGenerales\Usuarios\Movilizacion.php', '2020-05-06 00:00:00', '2020-05-06 00:00:00');
        INSERT INTO siemprea_bspi_datgen.formularios
            (MODULO_COD, FORMULARIO_NOM, FORMULARIO_UBICACION_COMPONENTE, FORMULARIO_UBICACION_CONTROLLER, FORMULARIO_UBICACION_MODEL, created_at, updated_at)
        VALUES
            ('DATGEN', 'Paises', 'resources\js\components\datosGenerales\configuraciones\Paises.vue', 'app\Http\Controllers\DatosGenerales\Generalidades\PaisesApiController.php', 'app\DatosGenerales\Generalidades\Paises.php', '2020-05-06 00:00:00', '2020-05-06 00:00:00');

        INSERT INTO siemprea_bspi_datgen.formularios
            (MODULO_COD, FORMULARIO_NOM, FORMULARIO_UBICACION_COMPONENTE, FORMULARIO_UBICACION_CONTROLLER, FORMULARIO_UBICACION_MODEL, created_at, updated_at)
        VALUES
            ('DATGEN', 'Religiones', 'resources\js\components\datosGenerales\configuraciones\Religiones.vue', 'app\Http\Controllers\DatosGenerales\Usuarios\ReligionApiController.php', 'app\DatosGenerales\Usuarios\Religion.php', '2020-05-06 00:00:00', '2020-05-06 00:00:00');

        INSERT INTO siemprea_bspi_datgen.formularios
            (MODULO_COD, FORMULARIO_NOM, FORMULARIO_UBICACION_COMPONENTE, FORMULARIO_UBICACION_CONTROLLER, FORMULARIO_UBICACION_MODEL, created_at, updated_at)
        VALUES
            ('DATGEN', 'TiposDeCasa', 'resources\js\components\datosGenerales\configuraciones\TiposDeCasa.vue', 'app\Http\Controllers\DatosGenerales\Usuarios\TiposDeCasaApiController.php', 'app\DatosGenerales\Usuarios\TiposDeCasa.php', '2020-05-06 00:00:00', '2020-05-06 00:00:00');

        INSERT INTO siemprea_bspi_datgen.formularios
            (MODULO_COD, FORMULARIO_NOM, FORMULARIO_UBICACION_COMPONENTE, FORMULARIO_UBICACION_CONTROLLER, FORMULARIO_UBICACION_MODEL, created_at, updated_at)
        VALUES
            ('DATGEN', 'TiposDeOrganizacion', 'resources\js\components\datosGenerales\configuraciones\TiposDeOrganizacion.vue', 'app\Http\Controllers\DatosGenerales\Usuarios\TipoDeOrganizacionApiController.php', 'app\DatosGenerales\Usuarios\TipoDeOrganizacion.php', '2020-05-06 00:00:00', '2020-05-06 00:00:00');

        INSERT INTO siemprea_bspi_datgen.formularios
            (MODULO_COD, FORMULARIO_NOM, FORMULARIO_UBICACION_COMPONENTE, FORMULARIO_UBICACION_CONTROLLER, FORMULARIO_UBICACION_MODEL, created_at, updated_at)
        VALUES
            ('DATGEN', 'TiposDeSangre', 'resources\js\components\datosGenerales\configuraciones\TiposDeSangre.vue', 'app\Http\Controllers\DatosGenerales\Usuarios\TiposDeSangreApiController.php', 'app\DatosGenerales\Usuarios\TiposDeSangre.php', '2020-05-06 00:00:00', '2020-05-06 00:00:00');