ALTER TABLE `siemprea_bspi_datgen`.`configuracion` 
ADD COLUMN `INTENTO_FALLIDO` INT NOT NULL AFTER `ADMIN_EMAIL`,
ADD COLUMN `TIEMPO_BLOQUEO` INT NOT NULL AFTER `INTENTO_FALLIDO`;
ADD COLUMN `TIEMPO_ACTUALIZACION_CLAVE` INT NOT NULL AFTER `TIEMPO_BLOQUEO`;
