<?php

namespace App\GestionHospitalaria\ConsultaExtena;

use Illuminate\Database\Eloquent\Model;

class Antecedente extends Model
{
    //
    protected $fillable = [
        'ANTECEDENTE_COD', 'USER_ID', 'CITA_COD', 'ANTECEDENTE_MOTIVO_CONSULTA', 'ANTECEDENTE_PERSONALES', 'ANTECEDENTE_CARDIOPATIA', 'ANTECEDENTE_TUBERCULOSIS', 'ANTECEDENTE_DIABETES', 'ANTECEDENTE_ENFC_VASCULAR', 'ANTECEDENTE_HIPERTENSION', 'ANTECEDENTE_CANCER', 'ANTECEDENTE_ENFMENTAL', 'ANTECEDENTE_ENFINFECCIOSA', 'ANTECEDENTE_MALFORMACION', 'ANTECEDENTE_OTRA', 'ANTECEDENTE_ENFERMEDAD_ACTUAL_PROBLEMA', 'ANTECEDENTE_EVOLUCION', 'ANTECEDENTE_REVISION_ACTUAL_ORGANO_SISTEMA', 'ANTECEDENTE_LOGIC_ESTADO', 'US_COD_CREATED_UPDATED'
    ];
    protected $connection = 'mysql_gestion_hospitalaria';
    protected $table = 'antecedentes';
    protected $primaryKey = 'ANTECEDENTE_COD';
}
